import { Link } from "react-router-dom";
import PracticePapersSidebar from "../Components/PracticePapersSidebar";
import Header from "../Components/Header";

const images = [
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-a-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-a-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-a-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-a-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-b-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-b-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-b-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-b-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-c-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-c-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-c-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-c-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-d-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-d-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-d-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-d-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-e-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-e-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-e-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-e-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-f-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-f-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-f-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-f-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-g-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-g-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-g-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-g-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-h-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-h-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-h-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-h-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-i-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-i-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-i-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-i-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-j-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-j-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-j-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-j-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-k-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-k-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-k-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-k-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-l-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-l-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-l-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-l-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-m-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-m-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-m-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-m-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-n-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-n-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-n-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-n-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-o-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-o-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-o-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-o-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-p-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-p-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-p-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-p-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-q-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-q-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-q-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-q-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-r-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-r-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-r-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-r-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-s-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-s-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-s-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-s-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-t-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-t-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-t-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-t-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-u-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-u-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-u-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-u-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-v-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-v-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-v-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-v-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-w-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-w-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-w-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-w-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-x-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-x-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-x-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-x-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-y-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-y-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-y-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-y-v4-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-z-v1-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-z-v2-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-z-v3-medium.jpg",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-z-v4-medium.jpg",
];

const redirectUrls = [
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-a-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-a-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-a-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-a-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-a-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-a-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-a-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-a-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-b-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-b-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-b-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-b-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-b-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-b-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-b-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-b-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-c-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-c-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-c-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-c-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-c-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-c-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-c-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-c-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-d-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-d-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-d-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-d-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-d-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-d-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-d-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-d-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-e-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-e-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-e-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-e-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-e-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-e-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-e-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-e-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-f-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-f-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-f-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-f-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-f-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-f-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-f-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-f-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-g-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-g-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-g-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-g-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-g-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-g-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-g-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-g-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-h-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-h-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-h-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-h-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-h-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-h-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-h-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-h-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-i-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-i-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-i-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-i-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-i-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-i-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-i-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-i-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-j-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-j-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-j-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-j-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-j-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-j-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-j-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-j-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-k-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-k-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-k-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-k-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-k-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-k-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-k-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-k-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-l-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-l-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-l-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-l-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-l-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-l-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-l-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-l-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-m-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-m-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-m-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-m-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-m-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-m-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-m-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-m-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-n-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-n-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-n-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-n-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-n-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-n-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-n-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-n-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-o-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-o-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-o-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-o-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-o-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-o-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-o-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-o-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-p-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-p-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-p-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-p-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-p-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-p-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-p-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-p-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-q-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-q-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-q-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-q-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-q-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-q-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-q-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-q-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-r-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-r-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-r-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-r-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-r-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-r-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-r-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-r-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-s-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-s-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-s-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-s-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-s-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-s-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-s-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-s-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-t-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-t-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-t-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-t-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-t-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-t-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-t-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-t-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-u-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-u-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-u-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-u-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-u-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-u-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-u-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-u-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-v-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-v-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-v-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-v-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-v-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-v-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-v-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-v-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-w-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-w-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-w-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-w-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-w-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-w-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-w-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-w-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-x-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-x-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-x-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-x-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-x-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-x-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-x-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-x-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-y-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-y-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-y-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-y-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-y-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-y-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-y-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-y-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-z-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-z-v1.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-z-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-z-v2.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-z-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-z-v3.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-z-v4.html",
  "https://www.dadsworksheets.com/worksheets/addition/spaceship-math-z-v4.html",
];

const groupHeaders = [
  "Spaceship Math Addition A: 1+2, 2+1, 1+3, 3+1",
  "Spaceship Math Addition B: 1+4, 4+1, 1+1",
  "Spaceship Math Addition C: 1+5, 5+1, 2+2",
  "Spaceship Math Addition D: 1+6, 6+1, 3+3",
  "Spaceship Math Addition E: 1+7, 7+1, 4+4",
  "Spaceship Math Addition F: 1+8, 8+1, 5+5",
  "Spaceship Math Addition G: 1+9, 9+1, 0 + Any Number",
  "Spaceship Math Addition H: 2+3, 3+2, 6+6",
  "Spaceship Math Addition I: 4+2, 2+4, 7+7",
  "Spaceship Math Addition J: 5+2, 2+5, 8+8",
  "Spaceship Math Addition K: 6+2, 2+6, 9+9",
  "Spaceship Math Addition L: 7+2, 2+7, 4+7, 7+4",
  "Spaceship Math Addition M: 8+2, 2+8, 8+6, 6+8",
  "Spaceship Math Addition N: 9+2, 2+9, 9+6, 6+9",
  "Spaceship Math Addition O: 4+3, 3+4, 6+7, 7+6",
  "Spaceship Math Addition P: 5+3, 3+5, 7+8, 8+7",
  "Spaceship Math Addition Q: 5+8, 8+5, 7+9, 9+7",
  "Spaceship Math Addition R: 6+3, 3+6, 5+9, 9+5",
  "Spaceship Math Addition S: 7+3, 3+7, 8+9, 9+8",
  "Spaceship Math Addition T: 8+3, 3+8, 4+9, 9+4",
  "Spaceship Math Addition U: 9+3, 3+9, 5+7, 7+5",
  "Spaceship Math Addition V: 4+5, 5+4, 4+8, 8+4",
  "Spaceship Math Addition W: 4+6, 6+4, 5+6, 6+5",
  "Spaceship Math Addition X: All Problems Practice",
  "Spaceship Math Addition Y: All Problems Practice",
  "Spaceship Math Addition Z: All Problems (No Zero)",
];

function PracticePapers() {
  return (
    <>
      <Header />
      <div className="mt-10 pt-32 flex justify-center">
        <div className="ml-16 2xl:ml-0">
          <PracticePapersSidebar />
        </div>
        <div className="flex w-full max-w-7xl">
          <div className="flex flex-col">
            <h1 id="pageTitle" className="mt-1 mb-2 pl-1 text-left">
              Addition Math Facts Worksheets
            </h1>
            <p>
              These addition worksheets are similar to the
              <a
                className="mx-1 text-blue400"
                href="https://www.dadsworksheets.comhttps://www.dadsworksheets.com/2008/09/05/an-overview-of-rocket-math.html"
              >
                <i>RocketMath</i>
              </a>
              , <i>Wolf Swamp</i> or <i>Mastering Math Facts</i> addition
              worksheets used at many schools. These are typically one minute,
              timed tests. Try my super entertaining
              <a
                className="mx-1 text-blue400"
                href="https://www.dadsworksheets.comhttps://www.dadsworksheets.com/timer.html"
              >
                online timer
              </a>{" "}
              if you or your kids are into silly sounds!
            </p>
            <div className="grid grid-cols-4">
              {images.map((img, i) => (
                <>
                  {i % 4 === 0 && (
                    <h3 className="col-span-4 mt-6 mb-2">
                      {groupHeaders[i / 4]}
                    </h3>
                  )}
                  <Link href={redirectUrls[i]}>
                    <img
                      src={img}
                      alt=""
                      className="transition-all hover:scale-105"
                    />
                  </Link>
                </>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default PracticePapers;
